title: Jeff DeWolfe
logo: "/images/Bitmoji-Placeholder.jpg"
description: A versatile professional with experience in multiple industries, I am currently seeking an entry-level position as a programmer. With a penchant for problem-solving and an unquenchable thirst for knowledge, I approach every goal with a dogged need for perfection.
theme: jekyll-theme-minimal
