title: Jeff DeWolfe
logo: "/images/Bitmoji-Placeholder.jpg"
description: A versatile professional with experience in multiple industries, I am currently seeking an entry-level position as a programmer. With a penchant for problem-solving and an unquenchable thirst for knowledge, I approach every goal with a dogged need for perfection. <br><br><a href="mailto:jadewolfe@gmail.com" target="_blank">Send Me an Email</a><br><br><a href="https://www.linkedin.com/in/J-DeWolfe">Visit My LinkedIn Profile</a>
email: jaDewolfe@gmail.com
theme: jekyll-theme-minimal
