title: J DeWolfe
description: A versatile professional with a penchant for problem-solving now seeking an entry-level position as a programmer.

With an unquenchable thirst for knowledge and a dogged need for perfection, I approach every goal with a tenacious work ethic.
theme: jekyll-theme-minimal
